baseURL = 'https://alma.ucr.ac.cr/'
languageCode = 'es'
title = 'ALMA'
theme = 'alma'

ignoreFiles = ["\\.org$"]

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
    params.icon = 'bx bx-home'
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20
    params.icon = 'bx bx-news'
  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30
    params.icon = 'bx bx-book'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
[params]
  math = true
