baseURL = 'https://alma.ucr.ac.cr/'
languageCode = 'es'
title = 'ALMA'
theme = 'alma'
ignoreFiles = ["\\.org$"]
defaultContentLanguage = 'es'

[params]
  math = true
  description = 'Archivo Libre para Material Académico'

[languages]
  [languages.es]
    languageCode = 'es'
    languageName = 'Español'
    weight = 1
    [languages.es.menus]
      [[languages.es.menus.main]]
        identifier = 'home'
        pageRef = '/'
        weight = 10
        params.icon = 'bx bx-home'
      [[languages.es.menus.main]]
        identifier = 'pub'
        pageRef = '/pub'
        weight = 20
        params.icon = 'bx bx-news'
      [[languages.es.menus.main]]
        identifier = 'subjects'
        pageRef = '/tags'
        weight = 30
        params.icon = 'bx bx-book'
  [languages.en]
    languageCode = 'en'
    languageName = 'English'
    weight = 2
    [languages.en.menus]
      [[languages.en.menus.main]]
        identifier = 'home'
        pageRef = '/'
        weight = 10
        params.icon = 'bx bx-home'
      [[languages.en.menus.main]]
        identifier = 'pub'
        pageRef = '/pub'
        weight = 20
        params.icon = 'bx bx-news'
      [[languages.en.menus.main]]
        identifier = 'subjects'
        pageRef = '/tags'
        weight = 30
        params.icon = 'bx bx-book'

[markup]
  [markup.highlight]
    style = 'solarized-dark256'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
